// Seed script: creates a complete 25-language card for testing
// Usage: npx tsx scripts/seed-full-card.ts

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const CARD = {
    tipo: "chunk" as const,
    contexto: "Num café em Berlim, pedindo educadamente.",
    frentePt: "Eu gostaria de um café, por favor.",
    frentePtNorm: "eu gostaria de um cafe por favor",
    notaGlobal:
        "O condicional de polidez existe em quase todas as línguas europeias. Em CJK, polidez se expressa por sufixos verbais e honoríficos, não por modo verbal.",
    objetivo: "Treinar pedido educado com condicional de polidez",
    idiomasPrincipais: ["DE", "FR", "JA"],
    familiaContraste: "cjk",
    nivel: "a1" as const,
    categoria: "pedido" as const,
    source: "manual" as const,
    quality: "gold" as const,
};

const BLOCOS = [
    {
        langCode: "DE",
        natural: "Ich hätte gerne einen Kaffee, bitte.",
        romanizacao: "—",
        variacaoNativa: "Könnt ich 'nen Kaffee kriegen?",
        literal: "Eu teria com-prazer um café, por-favor.",
        padrao: "Konjunktiv II de haben + gerne + Akk",
        gramatica: "hätte = Konj. II de haben; einen = acusativo masc.",
        obs: "hätte gerne é a forma padrão de pedir educadamente.",
        erroTipico: "Usar 'Ich will' (soa rude) em vez de 'Ich hätte gerne'.",
        contraste: "EN usa would like; DE usa Konjunktiv II — estrutura similar.",
        armadilha: "einen é acusativo masculino; der Kaffee → einen Kaffee.",
        padraoReutilizavel: "Ich hätte gerne [Akk], bitte.",
        gatilho: "Qualquer pedido em restaurante, café, loja.",
        registro: "neutro-polido",
        sinonimos: "Ich möchte gerne…; Könnten Sie mir… bringen?",
        antonimo: "Ich will kein… (recusa)",
        collocations: "einen Kaffee bestellen, bitte schön",
        campoSemantico: "Gastronomie, Bestellung, Höflichkeit",
        registroVariacoes: "formal: Dürfte ich… bekommen?; coloquial: Krieg ich 'nen…?",
    },
    {
        langCode: "EN",
        natural: "I would like a coffee, please.",
        romanizacao: "—",
        variacaoNativa: "Can I get a coffee?",
        literal: "Eu iria gostar um café, por-favor.",
        padrao: "would + like + noun",
        gramatica: "would like = modal condicional de polidez",
        obs: "would like é a forma universal de pedido educado em inglês.",
        erroTipico: "Usar 'I want' (direto demais) em contexto formal.",
        contraste: "FR usa je voudrais (condicional); EN usa would like (modal).",
        armadilha: "a coffee (contável) vs. some coffee (incontável).",
        padraoReutilizavel: "I would like [noun], please.",
        gatilho: "Pedido educado em qualquer contexto anglófono.",
        registro: "neutro-polido",
        sinonimos: "Could I have…; May I have…; I'd like…",
        antonimo: "No, thank you (recusa educada)",
        collocations: "order a coffee, place an order",
        campoSemantico: "food & drink, polite requests",
        registroVariacoes: "formal: Might I request…; casual: Can I get…",
    },
    {
        langCode: "FR",
        natural: "Je voudrais un café, s'il vous plaît.",
        romanizacao: "—",
        variacaoNativa: "J'prendrais bien un p'tit café.",
        literal: "Eu quereria um café, se-vos agrada.",
        padrao: "conditionnel de vouloir + nom",
        gramatica: "voudrais = conditionnel présent de vouloir",
        obs: "je voudrais é o padrão de polidez em restaurantes.",
        erroTipico: "Usar 'je veux' (soa como exigência).",
        contraste: "IT usa vorrei (condizionale); mesma estratégia morfológica.",
        armadilha: "un café = expresso; café crème = com leite.",
        padraoReutilizavel: "Je voudrais [nom], s'il vous plaît.",
        gatilho: "Restaurante, padaria, qualquer comércio francófono.",
        registro: "neutro-polido",
        sinonimos: "Pourriez-vous me servir…; J'aimerais…",
        antonimo: "Non merci (recusa)",
        collocations: "commander un café, prendre un café",
        campoSemantico: "gastronomie, commande, politesse",
        registroVariacoes: "formal: Auriez-vous l'obligeance de…; fam: Un café, svp!",
    },
    {
        langCode: "IT",
        natural: "Vorrei un caffè, per favore.",
        romanizacao: "—",
        variacaoNativa: "Mi fa un caffè?",
        literal: "Quereria um café, por favor.",
        padrao: "condizionale di volere + nome",
        gramatica: "vorrei = condizionale presente di volere",
        obs: "vorrei é a forma padrão de pedido educado.",
        erroTipico: "Usar 'voglio' (direto demais).",
        contraste: "ES usa querría/quisiera; IT usa vorrei — ambos condicionais.",
        armadilha: "un caffè = espresso; caffè latte = com leite.",
        padraoReutilizavel: "Vorrei [nome], per favore.",
        gatilho: "Qualquer pedido em contexto italiano.",
        registro: "neutro-polido",
        sinonimos: "Potrei avere…; Mi piacerebbe…",
        antonimo: "No, grazie (recusa)",
        collocations: "ordinare un caffè, prendere un caffè",
        campoSemantico: "gastronomia, ordinazione, cortesia",
        registroVariacoes: "formal: Desidererei…; fam: Fammi un caffè!",
    },
    {
        langCode: "ES",
        natural: "Quisiera un café, por favor.",
        romanizacao: "—",
        variacaoNativa: "¿Me pone un café?",
        literal: "Quisera um café, por favor.",
        padrao: "subjuntivo imperfecto de querer + sustantivo",
        gramatica: "quisiera = imperfecto de subjuntivo (polidez)",
        obs: "quisiera/querría são intercambiáveis para polidez.",
        erroTipico: "Usar 'quiero' (soa imperativo).",
        contraste: "PT usa gostaria de; ES usa quisiera — etimologia diferente.",
        armadilha: "un café = espresso; café con leche = com leite.",
        padraoReutilizavel: "Quisiera [sustantivo], por favor.",
        gatilho: "Pedido educado em qualquer contexto hispanófono.",
        registro: "neutro-polido",
        sinonimos: "Me gustaría…; ¿Podría traerme…?",
        antonimo: "No, gracias (recusa)",
        collocations: "pedir un café, tomar un café",
        campoSemantico: "gastronomía, pedido, cortesía",
        registroVariacoes: "formal: ¿Sería tan amable de…?; fam: Ponme un café.",
    },
    {
        langCode: "JA",
        natural: "コーヒーを一つお願いします。",
        romanizacao: "kōhī o hitotsu onegai shimasu",
        variacaoNativa: "コーヒー、ちょうだい。",
        literal: "Café-OBJ um-por-favor-faço.",
        padrao: "[名詞]をお願いします",
        gramatica: "を = partícula de objeto; お願いします = fórmula de polidez",
        obs: "お願いします é a fórmula padrão de pedido educado.",
        erroTipico: "Omitir を ou usar ください (mais casual) em contexto formal.",
        contraste: "KO usa 주세요; JA usa お願いします — ambos sufixos de polidez.",
        armadilha: "一つ (hitotsu) é o contador genérico; para copos: 一杯 (ippai).",
        padraoReutilizavel: "[名詞]をお願いします。",
        gatilho: "Qualquer pedido educado em japonês.",
        registro: "polido (です/ます)",
        sinonimos: "〜をいただけますか; 〜をくださいませんか",
        antonimo: "結構です (kekkou desu = não, obrigado)",
        collocations: "注文する、お会計お願いします",
        campoSemantico: "飲食、注文、丁寧語",
        registroVariacoes: "keigo: 〜を頂戴できますでしょうか; casual: コーヒーちょうだい",
    },
    {
        langCode: "KO",
        natural: "커피 한 잔 주세요.",
        romanizacao: "keopi han jan juseyo",
        variacaoNativa: "커피 하나 줘.",
        literal: "Café um copo dê-por-favor.",
        padrao: "[명사] 주세요",
        gramatica: "주세요 = forma educada de 주다 (dar)",
        obs: "주세요 é o sufixo padrão de polidez para pedidos.",
        erroTipico: "Usar 줘 (casual) com estranhos — rude.",
        contraste: "JA usa お願いします; KO usa 주세요 — mesma função, formas diferentes.",
        armadilha: "한 잔 = um copo; 한 개 = uma unidade (genérico).",
        padraoReutilizavel: "[명사] 주세요.",
        gatilho: "Pedido educado em coreano.",
        registro: "존댓말 (polido)",
        sinonimos: "~을/를 부탁드립니다; ~을/를 주시겠어요?",
        antonimo: "괜찮아요 (gwenchanayo = tá bom assim)",
        collocations: "주문하다, 계산해 주세요",
        campoSemantico: "음식, 주문, 존댓말",
        registroVariacoes: "formal: ~을 부탁드리겠습니다; casual: 커피 줘",
    },
    {
        langCode: "ZH",
        natural: "请给我一杯咖啡。",
        romanizacao: "qǐng gěi wǒ yī bēi kāfēi",
        variacaoNativa: "来杯咖啡。",
        literal: "Por-favor dar eu um copo café.",
        padrao: "请 + verbo + objeto",
        gramatica: "请 = marcador de polidez; 给 = dar; 一杯 = um copo",
        obs: "请 no início marca polidez; pode-se omitir em contexto casual.",
        erroTipico: "Dizer 我要 sem 请 (soa brusco).",
        contraste: "JA usa fórmula no final; ZH usa 请 no início — posição oposta.",
        armadilha: "一杯 (yī bēi) usa classificador 杯 para bebidas.",
        padraoReutilizavel: "请给我[量词+名词]。",
        gatilho: "Pedido educado em mandarim.",
        registro: "neutro-polido",
        sinonimos: "麻烦您给我…; 我想要…",
        antonimo: "不用了，谢谢 (não preciso, obrigado)",
        collocations: "点咖啡, 买单",
        campoSemantico: "餐饮, 点餐, 礼貌用语",
        registroVariacoes: "formal: 劳驾，能否给我…; casual: 来杯咖啡",
    },
    {
        langCode: "RU",
        natural: "Я бы хотел кофе, пожалуйста.",
        romanizacao: "ya by khotel kofe, pozhaluysta",
        variacaoNativa: "Мне кофе, пожалуйста.",
        literal: "Eu [partícula condicional] queria café, por-favor.",
        padrao: "я бы хотел(а) + [сущ.], пожалуйста",
        gramatica: "бы + хотел = condicional; пожалуйста = por favor",
        obs: "я бы хотел é mais educado que я хочу (eu quero).",
        erroTipico: "Esquecer бы (muda de desejo para exigência).",
        contraste: "DE usa Konjunktiv II; RU usa бы + pretérito — lógica similar.",
        armadilha: "кофе é indeclinável e masculino (exceção).",
        padraoReutilizavel: "Я бы хотел(а) [сущ.], пожалуйста.",
        gatilho: "Pedido educado em russo.",
        registro: "neutro-polido",
        sinonimos: "Можно мне…; Не могли бы вы…",
        antonimo: "Нет, спасибо (não, obrigado)",
        collocations: "заказать кофе, попросить счёт",
        campoSemantico: "общепит, заказ, вежливость",
        registroVariacoes: "formal: Будьте любезны…; fam: Мне кофе.",
    },
    {
        langCode: "AR",
        natural: "أريد قهوة من فضلك.",
        romanizacao: "urīdu qahwa min faḍlak",
        variacaoNativa: "عطني قهوة.",
        literal: "Quero café de favor-teu.",
        padrao: "أريد + [اسم]، من فضلك",
        gramatica: "أريد = quero (1ª sing.); من فضلك = por favor (masc.)",
        obs: "Em árabe, أريد é aceitável com من فضلك para polidez.",
        erroTipico: "Usar أعطني (dê-me) sem من فضلك — soa brusco.",
        contraste: "HE usa אני רוצה (ani rotze); AR usa أريد — cognatos semíticos.",
        armadilha: "من فضلك (masc.) vs. من فضلِك (fem.) — muda por gênero do ouvinte.",
        padraoReutilizavel: "أريد [اسم]، من فضلك.",
        gatilho: "Pedido educado em árabe.",
        registro: "neutro-polido",
        sinonimos: "هل يمكنني الحصول على…; لو سمحت…",
        antonimo: "لا شكراً (não, obrigado)",
        collocations: "طلب قهوة، الحساب من فضلك",
        campoSemantico: "مطعم، طلب، أدب",
        registroVariacoes: "formal: هل تتكرم بتقديم…; fam: عطني…",
    },
    {
        langCode: "SV",
        natural: "Jag skulle vilja ha en kaffe, tack.",
        romanizacao: "—",
        variacaoNativa: "Kan jag få en kaffe?",
        literal: "Eu deveria querer ter um café, obrigado.",
        padrao: "jag skulle vilja ha + [subst.]",
        gramatica: "skulle vilja = condicional de polidez dupla",
        obs: "skulle vilja ha é a forma mais educada, com duplo condicional.",
        erroTipico: "Usar 'jag vill ha' (direto, ok entre amigos, rude com estranhos).",
        contraste: "NO usa 'jeg vil gjerne ha'; SV mais formal com 'skulle vilja'.",
        armadilha: "en kaffe (utr.) — artigo indefinido en, não ett.",
        padraoReutilizavel: "Jag skulle vilja ha [subst.], tack.",
        gatilho: "Pedido educado em sueco.",
        registro: "polido",
        sinonimos: "Kan jag få…; Skulle det vara möjligt att…",
        antonimo: "Nej tack (não, obrigado)",
        collocations: "beställa en kaffe, be om notan",
        campoSemantico: "mat & dryck, beställning, artighet",
        registroVariacoes: "formal: Vore det möjligt att…; fam: En kaffe, tack!",
    },
    {
        langCode: "NO",
        natural: "Jeg vil gjerne ha en kaffe, takk.",
        romanizacao: "—",
        variacaoNativa: "Kan jeg få en kaffe?",
        literal: "Eu quero com-prazer ter um café, obrigado.",
        padrao: "jeg vil gjerne ha + [subst.]",
        gramatica: "vil gjerne = querer com prazer (polidez via advérbio)",
        obs: "gjerne suaviza o pedido; sem ele, vil ha = quero (direto).",
        erroTipico: "Esquecer gjerne (muda de pedido educado para exigência).",
        contraste: "SV usa 'skulle vilja ha' (mais formal); NO mais direto com 'vil gjerne ha'.",
        armadilha: "en kaffe (masc.) — gênero diferente do sueco.",
        padraoReutilizavel: "Jeg vil gjerne ha [subst.], takk.",
        gatilho: "Pedido educado em norueguês.",
        registro: "neutro-polido",
        sinonimos: "Kunne jeg fått…; Jeg lurer på om jeg kan få…",
        antonimo: "Nei takk (não, obrigado)",
        collocations: "bestille en kaffe, be om regningen",
        campoSemantico: "mat & drikke, bestilling, høflighet",
        registroVariacoes: "formal: Ville det være mulig å…; fam: En kaffe, takk!",
    },
    {
        langCode: "NL",
        natural: "Ik zou graag een koffie willen, alstublieft.",
        romanizacao: "—",
        variacaoNativa: "Mag ik een koffietje?",
        literal: "Eu iria com-prazer um café querer, se-agrada-lhe.",
        padrao: "ik zou graag + [zn.] + willen",
        gramatica: "zou = condicional; graag = com prazer; willen = querer (V-final)",
        obs: "zou graag willen é a forma mais educada; V-final típica do holandês.",
        erroTipico: "Usar 'ik wil' (direto, aceitável mas menos educado).",
        contraste: "DE usa möchte/hätte gerne; NL usa zou graag willen — estrutura mais longa.",
        armadilha: "koffietje (diminutivo) é mais amigável que koffie.",
        padraoReutilizavel: "Ik zou graag [zn.] willen, alstublieft.",
        gatilho: "Pedido educado em holandês.",
        registro: "polido",
        sinonimos: "Mag ik…; Zou ik… kunnen krijgen?",
        antonimo: "Nee, dank u (não, obrigado)",
        collocations: "een koffie bestellen, afrekenen",
        campoSemantico: "eten & drinken, bestelling, beleefdheid",
        registroVariacoes: "formal: Zou u zo vriendelijk willen zijn om…; fam: Doe mij maar een koffie!",
    },
    {
        langCode: "DA",
        natural: "Jeg vil gerne have en kaffe, tak.",
        romanizacao: "—",
        variacaoNativa: "Kan jeg få en kaffe?",
        literal: "Eu quero com-prazer ter um café, obrigado.",
        padrao: "jeg vil gerne have + [subst.]",
        gramatica: "vil gerne = quero com prazer (advérbio suaviza)",
        obs: "gerne funciona como gjerne em NO — suaviza o pedido.",
        erroTipico: "Omitir gerne (muda o tom para imperativo).",
        contraste: "NO usa gjerne; DA usa gerne — cognatos escandinavos 1:1.",
        armadilha: "en kaffe (fælles køn) — gênero comum.",
        padraoReutilizavel: "Jeg vil gerne have [subst.], tak.",
        gatilho: "Pedido educado em dinamarquês.",
        registro: "neutro-polido",
        sinonimos: "Kunne jeg få…; Jeg ville gerne bede om…",
        antonimo: "Nej tak (não, obrigado)",
        collocations: "bestille en kaffe, bede om regningen",
        campoSemantico: "mad & drikke, bestilling, høflighed",
        registroVariacoes: "formal: Ville det være muligt at…; fam: En kaffe, tak!",
    },
    {
        langCode: "FI",
        natural: "Saisinko kahvin, kiitos.",
        romanizacao: "—",
        variacaoNativa: "Yks kahvi, kiitos.",
        literal: "Poderia-eu-Q café-GEN, obrigado.",
        padrao: "saisinko + [partitiv/gen.], kiitos",
        gramatica: "saisinko = condicional de saada + -ko (interrogativo)",
        obs: "Finlandês marca polidez com condicional + interrogativo.",
        erroTipico: "Usar haluan (quero) sem -ko — soa como exigência.",
        contraste: "HU usa szeretnék (condicional); FI usa condicional + interrogativo.",
        armadilha: "kahvin (genitivo) vs. kahvia (partitivo) — o genitivo implica 'um inteiro'.",
        padraoReutilizavel: "Saisinko [subst.], kiitos.",
        gatilho: "Pedido educado em finlandês.",
        registro: "polido",
        sinonimos: "Voisinko saada…; Olisiko mahdollista saada…",
        antonimo: "Ei kiitos (não, obrigado)",
        collocations: "tilata kahvi, pyytää lasku",
        campoSemantico: "ruoka & juoma, tilaus, kohteliaisuus",
        registroVariacoes: "formal: Olisitteko ystävällinen ja…; fam: Yks kahvi!",
    },
    {
        langCode: "BCS",
        natural: "Želio bih kafu, molim.",
        romanizacao: "—",
        variacaoNativa: "Daj mi kafu.",
        literal: "Desejado teria café, peço.",
        padrao: "želio/željela bih + [imenica], molim",
        gramatica: "bih = condicional de biti; želio = particípio de željeti",
        obs: "bih + particípio = condicional; molim = por favor.",
        erroTipico: "Omitir bih (muda para pretérito, não condicional).",
        contraste: "RU usa бы + pretérito; BCS usa bih + particípio — estrutura cognata.",
        armadilha: "kafu (acusativo) — kafa → kafu na flexão.",
        padraoReutilizavel: "Želio/željela bih [imenica], molim.",
        gatilho: "Pedido educado em BCS.",
        registro: "neutro-polido",
        sinonimos: "Mogu li dobiti…; Da li bih mogao…",
        antonimo: "Ne, hvala (não, obrigado)",
        collocations: "naručiti kafu, tražiti račun",
        campoSemantico: "gastronomija, narudžba, učtivost",
        registroVariacoes: "formal: Da li biste bili ljubazni…; fam: Daj kafu!",
    },
    {
        langCode: "HU",
        natural: "Szeretnék egy kávét, kérem.",
        romanizacao: "—",
        variacaoNativa: "Egy kávét kérek.",
        literal: "Gostaria-eu um café-ACC, peço.",
        padrao: "szeretnék + [főnév + -t], kérem",
        gramatica: "szeretnék = condicional de szeret; kávét = acusativo de kávé",
        obs: "szeretnék (condicional) é mais educado que kérek (indicativo).",
        erroTipico: "Usar akarok (quero) — brusco demais.",
        contraste: "FI usa condicional + interrogativo; HU usa só condicional.",
        armadilha: "kávét — sufixo -t marca acusativo (obrigatório).",
        padraoReutilizavel: "Szeretnék [főnév + -t], kérem.",
        gatilho: "Pedido educado em húngaro.",
        registro: "polido",
        sinonimos: "Kaphatnék…; Lenne szíves…",
        antonimo: "Nem, köszönöm (não, obrigado)",
        collocations: "kávét rendelni, számlát kérni",
        campoSemantico: "gasztronómia, rendelés, udvariasság",
        registroVariacoes: "formal: Megkérhetném…; fam: Egy kávét!",
    },
    {
        langCode: "CS",
        natural: "Chtěl bych kávu, prosím.",
        romanizacao: "—",
        variacaoNativa: "Dáte mi kafe?",
        literal: "Querido estaria café, peço.",
        padrao: "chtěl/chtěla bych + [podst.], prosím",
        gramatica: "bych = condicional 1ª pessoa; chtěl = particípio de chtít",
        obs: "bych + particípio = condicional; estrutura eslava padrão.",
        erroTipico: "Usar chci (quero, indicativo) — soa brusco.",
        contraste: "PL usa chciałbym (aglutinado); CS separa chtěl + bych.",
        armadilha: "kávu (acusativo feminino) — káva → kávu.",
        padraoReutilizavel: "Chtěl/chtěla bych [podst.], prosím.",
        gatilho: "Pedido educado em tcheco.",
        registro: "neutro-polido",
        sinonimos: "Mohl bych dostat…; Bylo by možné…",
        antonimo: "Ne, děkuji (não, obrigado)",
        collocations: "objednat kávu, požádat o účet",
        campoSemantico: "gastronomie, objednávka, zdvořilost",
        registroVariacoes: "formal: Směl bych poprosit o…; fam: Dej mi kafe!",
    },
    {
        langCode: "PL",
        natural: "Chciałbym kawę, proszę.",
        romanizacao: "—",
        variacaoNativa: "Poproszę kawę.",
        literal: "Quereria-eu café-ACC, peço.",
        padrao: "chciałbym/chciałabym + [rzecz.], proszę",
        gramatica: "chciałbym = condicional aglutinado (chciał + by + m)",
        obs: "Em polonês, a partícula condicional by se aglutina ao verbo.",
        erroTipico: "Usar chcę (quero, indicativo) em contexto formal.",
        contraste: "CS separa chtěl + bych; PL aglutina chciał+by+m — mesma raiz eslava.",
        armadilha: "kawę (acusativo) — kawa → kawę.",
        padraoReutilizavel: "Chciałbym/chciałabym [rzecz.], proszę.",
        gatilho: "Pedido educado em polonês.",
        registro: "neutro-polido",
        sinonimos: "Czy mógłbym dostać…; Poproszę…",
        antonimo: "Nie, dziękuję (não, obrigado)",
        collocations: "zamówić kawę, poprosić o rachunek",
        campoSemantico: "gastronomia, zamówienie, uprzejmość",
        registroVariacoes: "formal: Czy byłby Pan uprzejmy…; fam: Daj kawę!",
    },
    {
        langCode: "TR",
        natural: "Bir kahve alabilir miyim, lütfen?",
        romanizacao: "—",
        variacaoNativa: "Bir kahve, lütfen.",
        literal: "Um café pegar-poder-eu-Q, por-favor?",
        padrao: "[nesne] + alabilir miyim, lütfen?",
        gramatica: "-abilir = modal de possibilidade; miyim = interrogativo 1ª pessoa",
        obs: "alabilir miyim é o padrão de polidez com possibilidade + interrogativo.",
        erroTipico: "Usar istiyorum (quero) sem miyim — menos educado.",
        contraste: "FI usa -ko; TR usa miyim — ambos interrogativos como polidez.",
        armadilha: "Turco usa aglutinação: al-abil-ir mi-y-im = pegar-pode-AORIST-Q-1SG.",
        padraoReutilizavel: "[nesne] alabilir miyim, lütfen?",
        gatilho: "Pedido educado em turco.",
        registro: "polido",
        sinonimos: "Rica etsem…; … verir misiniz?",
        antonimo: "Hayır, teşekkürler (não, obrigado)",
        collocations: "kahve sipariş etmek, hesabı istemek",
        campoSemantico: "yiyecek & içecek, sipariş, nezaket",
        registroVariacoes: "formal: … lütfeder misiniz?; fam: Bir kahve ver.",
    },
    {
        langCode: "TH",
        natural: "ขอกาแฟหนึ่งแก้วครับ/ค่ะ",
        romanizacao: "khǎw kaafɛɛ nʉ̀ng kɛ̂ɛw khráp/khâ",
        variacaoNativa: "เอากาแฟ",
        literal: "Peço café um copo partícula-polidez.",
        padrao: "ขอ + [คำนาม] + ครับ/ค่ะ",
        gramatica: "ขอ = peço (polidez); ครับ = partícula masc.; ค่ะ = fem.",
        obs: "ขอ é mais educado que เอา (quero/pego).",
        erroTipico: "Omitir ครับ/ค่ะ — soa brusco sem partícula de polidez.",
        contraste: "VI usa cho tôi (dê-me); TH usa ขอ (peço) — ambos verbos de polidez.",
        armadilha: "ครับ (masc.) vs. ค่ะ (fem.) — depende de quem fala, não do ouvinte.",
        padraoReutilizavel: "ขอ [คำนาม] ครับ/ค่ะ",
        gatilho: "Pedido educado em tailandês.",
        registro: "polido",
        sinonimos: "รบกวน…; ช่วย … ด้วยครับ/ค่ะ",
        antonimo: "ไม่เอาครับ/ค่ะ (não quero)",
        collocations: "สั่งกาแฟ, ขอบิล",
        campoSemantico: "อาหาร, การสั่ง, มารยาท",
        registroVariacoes: "formal: กรุณา…ด้วยครับ; fam: เอากาแฟ",
    },
    {
        langCode: "VI",
        natural: "Cho tôi một ly cà phê, xin cảm ơn.",
        romanizacao: "—",
        variacaoNativa: "Cho mình cà phê đi.",
        literal: "Dê eu um copo café, peço agradeço.",
        padrao: "cho tôi + [danh từ] + xin cảm ơn",
        gramatica: "cho = dar/para; tôi = eu; xin = pedir (polidez)",
        obs: "cho tôi é a forma direta mas educada; xin adiciona polidez.",
        erroTipico: "Omitir xin/cảm ơn — soa como ordem.",
        contraste: "TH usa ขอ; VI usa cho — ambos verbos de polidez direta.",
        armadilha: "ly (sul) vs. cốc (norte) = copo — variação regional.",
        padraoReutilizavel: "Cho tôi [danh từ], xin cảm ơn.",
        gatilho: "Pedido educado em vietnamita.",
        registro: "neutro-polido",
        sinonimos: "Làm ơn cho tôi…; Tôi muốn…",
        antonimo: "Không, cảm ơn (não, obrigado)",
        collocations: "gọi cà phê, tính tiền",
        campoSemantico: "ẩm thực, gọi món, lịch sự",
        registroVariacoes: "formal: Xin vui lòng cho tôi…; fam: Cho mình… đi",
    },
    {
        langCode: "HE",
        natural: "אני רוצה קפה, בבקשה.",
        romanizacao: "ani rotze kafe, bevakasha",
        variacaoNativa: "תן לי קפה.",
        literal: "Eu quero café, por-favor.",
        padrao: "אני רוצה + [שם עצם], בבקשה",
        gramatica: "רוצה = quero (presente); בבקשה = por favor",
        obs: "Hebraico não tem condicional de polidez; בבקשה supre a função.",
        erroTipico: "Omitir בבקשה — muda de pedido para exigência.",
        contraste: "AR usa أريد (quero) + من فضلك; HE usa רוצה + בבקשה — cognatos semíticos.",
        armadilha: "רוצה muda por gênero: רוצה (m.) / רוצָה (f.).",
        padraoReutilizavel: "אני רוצה [שם עצם], בבקשה.",
        gatilho: "Pedido educado em hebraico.",
        registro: "neutro",
        sinonimos: "אפשר לקבל…; הייתי רוצה…",
        antonimo: "לא, תודה (não, obrigado)",
        collocations: "להזמין קפה, לבקש חשבון",
        campoSemantico: "מסעדנות, הזמנה, נימוס",
        registroVariacoes: "formal: האם אוכל לקבל…; fam: תן לי…",
    },
    {
        langCode: "EL",
        natural: "Θα ήθελα έναν καφέ, παρακαλώ.",
        romanizacao: "tha íthela énan kafé, parakaló",
        variacaoNativa: "Έναν καφέ, παρακαλώ.",
        literal: "Iria queria um café, peço.",
        padrao: "θα ήθελα + [ουσ.], παρακαλώ",
        gramatica: "θα ήθελα = condicional de θέλω (querer)",
        obs: "θα ήθελα é o padrão educado; θέλω (quero) é direto.",
        erroTipico: "Usar θέλω sem παρακαλώ — brusco.",
        contraste: "IT usa vorrei (condizionale); EL usa θα ήθελα — mesma estratégia.",
        armadilha: "έναν (acusativo masc.) — ο καφές → έναν καφέ.",
        padraoReutilizavel: "Θα ήθελα [ουσ.], παρακαλώ.",
        gatilho: "Pedido educado em grego.",
        registro: "neutro-polido",
        sinonimos: "Μπορώ να έχω…; Θα μπορούσα να…",
        antonimo: "Όχι, ευχαριστώ (não, obrigado)",
        collocations: "παραγγέλνω καφέ, ζητώ τον λογαριασμό",
        campoSemantico: "εστίαση, παραγγελία, ευγένεια",
        registroVariacoes: "formal: Θα ήταν δυνατόν να…; fam: Βάλε μου έναν καφέ!",
    },
    {
        langCode: "ID",
        natural: "Saya mau pesan kopi, tolong.",
        romanizacao: "—",
        variacaoNativa: "Kopi satu, ya.",
        literal: "Eu quero pedir café, ajude.",
        padrao: "saya mau pesan + [kata benda], tolong",
        gramatica: "mau = querer; pesan = pedir/encomendar; tolong = por favor",
        obs: "saya mau mais educado que aku mau (informal).",
        erroTipico: "Usar aku em contexto formal — desrespeitoso.",
        contraste: "VI usa cho tôi; ID usa saya mau pesan — mais formal com verbo 'pedir'.",
        armadilha: "tolong (ajude) vs. silakan (por favor para oferecer) — funções diferentes.",
        padraoReutilizavel: "Saya mau pesan [kata benda], tolong.",
        gatilho: "Pedido educado em indonésio.",
        registro: "neutro-polido",
        sinonimos: "Boleh saya minta…; Bisa tolong…",
        antonimo: "Tidak, terima kasih (não, obrigado)",
        collocations: "pesan kopi, minta bon",
        campoSemantico: "makanan & minuman, pesanan, kesopanan",
        registroVariacoes: "formal: Apakah saya bisa memesan…; fam: Kopi satu!",
    },
];

async function main() {
    console.log("Seeding full 25-language card...");

    // Delete old incomplete test card if exists
    const old = await prisma.card.findUnique({
        where: { frentePtNorm: CARD.frentePtNorm },
    });
    if (old) {
        await prisma.review.deleteMany({ where: { cardId: old.id } });
        await prisma.langDifficulty.deleteMany({ where: { cardId: old.id } });
        await prisma.cardTag.deleteMany({ where: { cardId: old.id } });
        await prisma.langBloco.deleteMany({ where: { cardId: old.id } });
        await prisma.card.delete({ where: { id: old.id } });
        console.log(`  Deleted old card ${old.id} (${old.seq})`);
    }

    const card = await prisma.card.create({
        data: {
            ...CARD,
            blocos: {
                create: BLOCOS,
            },
        },
        include: { blocos: true },
    });

    console.log(`  Created card #${card.seq} (${card.id})`);
    console.log(`  Blocos: ${card.blocos.length}/25`);
    console.log(`  Languages: ${card.blocos.map((b) => b.langCode).join(", ")}`);
    console.log("Done!");

    await prisma.$disconnect();
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
